version = 0.1
[default.deploy.parameters]
stack_name = "coffee-day-stack"
resolve_s3 = true
s3_prefix = "coffee-day-stack"
region = "us-east-1"
profile = "ng-antstack"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
